# Generated by Django 6.0.7 on 2026-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_uploadedimage_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
